[catalog.yazi]
name = "Yazi"
category = "misc"

[templates.yazi]
input_path = "yazi.toml"
output_path = "~/.config/yazi/flavors/noctalia.yazi/flavor.toml"
post_hook = "bash '{{ config_dir }}/apply.sh'"
