[catalog.vicinae]
name = "Vicinae"
category = "launcher"

[templates.vicinae]
input_path = "vicinae.toml"
output_path = "~/.local/share/vicinae/themes/noctalia.toml"
post_hook = "bash '{{ config_dir }}/apply.sh'"
