[General]
accent_color={{colors.primary.default.hex}}
background_color={{colors.surface.default.hex}}
user_accent_color={{colors.primary.default.hex}}
user_background_color={{colors.surface.default.hex}}